name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.7.0

      - name: Run ruff
        run: |
          ruff check .

  security:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install security tooling
        run: |
          python -m pip install --upgrade pip
          pip install bandit==1.7.10

      - name: Run bandit
        run: |
          bandit -r app scripts dashboard -ll

  dependency-audit:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pip-audit
        run: |
          # Temporary waiver: GHSA-wf7f-8fxf-xfxc (mlflow) tracked in docs/SECURITY.md
          pip-audit --format markdown --ignore-vuln GHSA-wf7f-8fxf-xfxc -r requirements.txt -r requirements-dev.txt

  test:
    needs:
      - lint
      - security
      - dependency-audit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pytest
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q
